### PR TITLE
Fix:Add/configure 404 page route for non-existing routes

### LINKED ISSUE #44: Add/configure 404 page route for non-existing routes
#### Issue
We don't have a 404 route/page for when a route/page does not exist in our web app: https://github.com/code-collabo/collabo-community-app

#### Expected solution
- Add/configure a 404 page route for when a route does not exist, so that when we type or paste a non-existing page route url in the browser, the user is redirected to the 404 page route.
- Note: We do not need you to add the figma design. Just use the basic things we have there in the app code for now.

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] 404 page route has been added/configured for when a route does not exist
- [ ] User is redirected to the 404 page route, if they type or paste a non-existing page route url in the browser
- [ ] Figma design is not added. Only the basic things we have there in the app code are used in this submisson.
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by tylerjusfly**
**This pull request makes the following changes**
* Fixes #44

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

 - [x] 404 page route has been added/configured for when a route does not exist
 - [x] User is redirected to the 404 page route, if they type or paste a non-existing page route url in the browser
 - [x] Figma design is not added. Only the basic things we have there in the app code are used in this submisson.
 - [x] I certify that I ran my checklist

Ping @code-collabo/web-app

### CODE REVIEW

**Comment by tylerjusfly** [comment]
Looking forward to the comments on what i might have missed. thanks. 👍🏿

**Comment by Ifycode** [comment]
Incase of next time @tylerjusfly please tag @code-collabo/community-mentors or @Ifycode in your comment. Preferrably tag @code-collabo/community-mentors so that I won't be the only one who receives notification.
Otherwise no one may receive notifications for your submission.
If I didn't check the PR list, I would not have seen this.

Reviewing your PR.

**Comment by Ifycode** [comment]
@tylerjusfly your issue is not linked to your PR. Help link issue properly.

Here's the markdown formatting for getting the PR linked to the issue:
````
- Fixes code-collabo/collabo-community-app#add-issue-number-here
````

**Comment by tylerjusfly** [comment]
@Ifycode i just linked PR to issue. did i do it correctly?

**Comment by Ifycode** [comment]
Yes, you did the linking well now @tylerjusfly 
That way, when the PR is merged, the issue linked to it automatically closes.

**Review by Ifycode — APPROVED** [review]
Nice work. The position of the file and how the 404 page shows up when needed is what we want to achieve.

Approved. Well done.

**Comment by tylerjusfly** [comment]
> Yes, you did the linking well now @tylerjusfly That way, when the PR is merged, the issue linked to it automatically closes.

oh, okay then, Thank you.

**Pull request merged**
