### PR TITLE
Fix: [Web App] Setup Nodejs Github actions/workflow for Collabo Community App

### PR DESCRIPTION
**Pull request by Akpjunior94**
**This pull request makes the following changes**
* Fixes code-collabo/collabo-community-app#68 

**General checklist**
- [X] File or folder now contains changes as specified in the issue i worked on
- [X] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

 - [X] Necessary config file have been added in the correct folder and/or position in the community app repo
 - [X] Configuration covers sending PR to the main or develop branch
 - [X] Configuration covers pushing to the main or develop branch
 - [X] Configuration covers node-version: [16.x, 17.x, 18.x, 19.x, 20.x]
 - [X] Workflow runs (at the bottom of the PR submitted)
 - [X] I certify that I ran my checklist

Ping @code-collabo/web-app

### CODE REVIEW

**Comment by Akpjunior94** [comment]
@Ifycode I am wondering how I will test since the .github folder has not been added initially to the project. does that mean you will merge first or do you have any idea towards this?

**Comment by oyenuga17** [comment]
LGTM @Ifycode

**Comment by oyenuga17** [comment]
@Akpjunior94  guess you figured it

**Comment by Ifycode** [comment]
Thank you for your review @oyenuga17 
@Akpjunior94 I can't remember how it goes, I'll let you know if we need to merge first once I confirm.

**Comment by Ifycode** [comment]
@Akpjunior94 I'm thinking this did not work because it was from a forked repo. You can close this PR, and try again since you now have access to the repository. Let's see how it goes this time.

**Pull request closed without merging**
