### PR TITLE
Fix eslint wiggle lines

### PR DESCRIPTION
**Pull request by Akpjunior94**
**This pull request makes the following changes**
* Fixes eslint-errros due to this code-collabo/collabo-community-app#70 

**General checklist**
- [X] File or folder now contains changes as specified in the issue i worked on
- [X] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

Replace this text with the testing checklist from the issue this pull request fixes.

Ping @code-collabo/web-app

### CODE REVIEW

**Comment by Akpjunior94** [comment]
@Festusali @Ifycode please have a look

**Comment by samuko-things** [comment]
@Akpjunior94, This looks good and the excess unwanted spaces are taken care of.

**Review by samuko-things — APPROVED** [review]
This is good as the unwanted excess spaces and semicolons are removed.

**Comment by Festusali** [comment]
@Akpjunior94 this PR is linked to another PR #70 

Is there a special reason for this decision? I suggest linking it to a particular issue instead f another PR.

**Comment by Akpjunior94** [comment]
> @Akpjunior94 this PR is linked to another PR #70
> 
> Is there a special reason for this decision? I suggest linking it to a particular issue instead f another PR.

This is fixing errors as a result of the linked fixed issue. @Ifycode confirms there is no need to creating a new issue because of that.

**Review by Ifycode — APPROVED** [review]
Example of separating concerns, we don't want to fix these kind of things that litters the whole files with unwanted changes in PRs that address specific issues. This is the reason why this is advised. Good linking it to the issue that provoked this 👍🏼

Approved @Akpjunior94

**Comment by Ifycode** [comment]
Incase of next time, check the contributing guide to check how, who or what to tag in PRs from the docs: https://docs.collabocommunity.com/contribute

**Pull request merged**
